USE [ICE_Project]
GO

/****** Object:  Index [OrderedStock]    Script Date: 2/16/2017 7:39:38 PM ******/
CREATE NONCLUSTERED INDEX [OrderedStock] ON [dbo].[Stock]
(
	[IngredientName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 75) ON [PRIMARY]
GO


